name: Build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install GHC and Cabal
        id: install-ghc-cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.6.2.0'

      - name: Cache Cabal store
        uses: actions/cache@v2
        with:
          path: ${{ steps.install-ghc-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-cabal-store

      - name: Add Cabal install directory to PATH
        run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          cabal update
          cabal install pandoc-2.16.1 markdown-unlit-0.5.1

      - name: Run build
        run: ./build.sh

      - name: Commit and push output chapters
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./doc
          git commit -m "Built chapter $(echo ${{ github.event.pull_request.head.ref }} | sed -r 's/(^|_)([a-z])/\U\2/g')"
          git push
